### ISSUE TITLE
Change start date without changing the end date

### ISSUE THREAD

**Issue by Janjiran** [hypeserver/react-date-range#464]
## Current behaviour
First you select the start date, then end date which is > then start date. After that, when you want to move the start date earlier, it will also change the end date.

## [FEATURE] Expected behaviour
Option for changing just the selected date.

Use-cases when editing start date:
- Case 1 : start date  = end date => expected : the end date will **not** be modified
- Case 2: start date > end date => expected : the end date will be modified 
- Case 3 : start date < end date => expected : the end date will **not** be modified

## Environment
Package Version: 1.0.3
React version: 16.9.0
Node version: 14.15.5
Browser: Chrome [90.0.4430.93]

**Comment by kamyar** [comment]
When you select the start date again the library assumes you are reselecting the range so wipes the end date as far as I know.
So this is expected behaviour.
In case I have misunderstood, please provide a screen capture gif/video to demonstrate the problem.
You can record it using something like [Giphy Capture](https://giphy.com/apps/giphycapture)  on [Our demo website](https://hypeserver.github.io/react-date-range/)

**Comment by strada** [comment]
I agree with @Janjiran on this behavior, and created a PR as an attempt to implement it.

**Comment by Janjiran** [comment]
Merged, thank you @strada and closing.
